# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

title: Javalia의 개발기록
email: javalia.javalia@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  개발한 내용을 기록하는 간소한 노트.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://garrettjavalia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  garrettjavalia

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap

ga_tracking: G-G7P8PXM5K6

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

defaults:
  - scope:
      path: 'assets'
      type: pages
    values:
      title: overried
      published: false

exclude:
  - assets/ 

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    posts:
      # Give the collection a name
      name: 글

collections:
  posts:
    permalink: "/:collection/:path/"
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#  - .sass-cache/
  # - .jekyll-cache/
  # - gemfiles/
  # - Gemfile
  # - Gemfile.lock
  # - node_modules/
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
